-- Create a table to store generated videos linked to a series
-- This table allows multiple video generations per series (1-to-many relationship).

-- Drop existing table if needed (WARNING: Data loss if run)
-- DROP TABLE IF EXISTS videos;

create table if not exists videos (
  id uuid default gen_random_uuid() primary key,
  
  -- Foreign key to series table.
  series_id uuid references series(id) on delete cascade not null,
  
  -- Direct link to PUBLIC users table (since we use Clerk + syncUser to public.users)
  user_id uuid references users(id) on delete cascade not null,
  
  -- The full script JSON object generated by Gemini
  script jsonb,
  
  -- Public URL of the generated voiceover audio file
  audio_url text,
  
  -- Specific voice model used for this generation
  voice_model text,
  
  -- Generated captions JSON structure
  captions jsonb,
  
  -- Array of public URLs for the generated images
  image_urls text[], 
  
  -- Status of the video generation
  status text default 'completed',
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Indices for faster retrieval
create index if not exists videos_series_id_idx on videos(series_id);
create index if not exists videos_user_id_idx on videos(user_id);
