import { LegalFooter } from "@/components/legal-footer";

export default function AIDisclosure() {
    return (
        <div className="flex min-h-screen flex-col">
            <main className="flex-1 container mx-auto px-4 py-12 max-w-4xl prose dark:prose-invert">
                <h1>AI Disclosure & End User Agreement</h1>
                <p className="text-muted-foreground">Last Updated: {new Date().toLocaleDateString()}</p>

                <h2>1. EU AI Act Compliance & Transparency</h2>
                <p>In compliance with the EU Artificial Intelligence Act and similar global transparency standards, Creator Cloud provides this disclosure to inform users about the nature of the content generated on our platform.</p>

                <h2>2. Nature of the Output</h2>
                <p><strong>The videos, images, voiceovers, and scripts generated by Creator Cloud are synthetic media created by Artificial Intelligence systems.</strong> They are not recordings of real events or real individuals unless explicitly based on user-provided source material.</p>

                <h2>3. The AI Models We Use</h2>
                <p>Our platform orchestrates several third-party foundation models to create this synthetic media, including:</p>
                <ul>
                    <li><strong>Google Gemini:</strong> For generating video scripts and structuring scenes.</li>
                    <li><strong>Deepgram:</strong> For text-to-speech (TTS) voiceover generation and audio transcription.</li>
                    <li><strong>Replicate:</strong> For generating the visual imagery present in the video scenes.</li>
                </ul>

                <h2>4. Watermarking and Metadata</h2>
                <p>To ensure transparency and prevent deceptive use of synthetic media, Creator Cloud embeds "AI-Generated" indicators into the resulting media where required by law. Users agree not to actively attempt to remove, obscure, or alter these disclosures.</p>

                <h2>5. User Acknowledgement</h2>
                <p>By checking the required consent forms during account creation and using the platform, you explicitly acknowledge that you are interacting with AI systems and that the output is synthetically generated.</p>
            </main>
            <LegalFooter />
        </div>
    );
}
